MaisAprendizado/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MaisAprendizado.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Seletor()
        {
            return View();
        }
        public IActionResult Aluno()
        {
            return View();
        }
        public IActionResult Professor()
        {
            return View();
        }
    }

}

MaisAprendizado/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MaisAprendizado.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

MaisAprendizado/Controllers/TelaPrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MaisAprendizado.Controllers
{
    public class TelaPrincipalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CriarCurso()
        {
            return View();
        }

        public IActionResult Perfil()
        {
            return View();
        }
    }
}

MaisAprendizado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="css/site.css">

    <title>+Aprendizados</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>
<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background:#FFFFFF;">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="img/logo2.png" width="247"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                    aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse justify-content-end" id="conteudoNavbarSuportado">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" asp-controller="Home" asp-action="Index">
                        HOME <span class="sr-only">
                            (Página
                            atual)
                        </span>
                    </a>
                    <a class="nav-item nav-link" href="#">SOBRE</a>
                    <a class="nav-item nav-link" href="#">CURSOS</a>

                </div>
                <form class="form-inline my-2 my-lg-0">
                    <a class="nav-item nav-link" href="@Url.Action(null, "Login")" style="color: #333333;">
                        <img src="img/8-512.png"
                             width="50">LOGIN |
                    </a>

                    <div class="text-center">
                       <a href="@Url.Action( "Seletor", "Cadastro")"<button class="btn btn-outline-danger my-2 my-sm-0">CADASTRAR</button></a>

                    </div>
                </form>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

            @RenderBody()


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <img src="img/logo2.png" width="100">
                </div>
                <div class="col-md-2">
                    <h4>company</h4>
                    <ul class="navbar-nav">
                        <li>
                            <a href="">HOME</a>
                        </li>
                        <li>
                            <a href="">SOBRE</a>
                        </li>
                        <li>
                            <a href="">CURSOS</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul>
                        <li>
                            <a href="">
                                <img src="img/download.png" width="50">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="img/download.jpg" width="50">
                            </a>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </footer>
</body>
</html>

MaisAprendizado/Views/Shared/_LayoutCadastro.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="~/css/seletor/estilo.css">

    <title>Escolha sua opção!</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background:#FFFFFF;">
            <a class="navbar-brand" href="#"><img src="~/img/logo2.png" width="247"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                    aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse justify-content-end" id="conteudoNavbarSuportado">
                <a class="nav-item nav-link" href="#" style="color: #333333;"> <img src="~/img/25694.svg" width="50"></a>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>




</body>


</html>

MaisAprendizado/Views/Shared/_LayoutCadastroAlunoProfessor.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="~/css/alunoProfessor.css">

    <title>Cadastro</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background:#FFFFFF;">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/img/logo2.png" width="247"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                    aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse justify-content-end" id="conteudoNavbarSuportado">
                <a class="nav-item nav-link" asp-controller="Home" asp-action="Index" style="color: #333333;"> <img src="~/img/25694.svg" width="50"></a>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()



    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>


</body>
</html>

MaisAprendizado/Views/Shared/_LayoutCriarCurso.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="~/css/criarCurso.css">

    <title>Criar Curso</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background:#FFFFFF;">
            <a class="navbar-brand" href="#"><img src="~/img/logo2.png" width="247"></a>


            <div class="collapse navbar-collapse justify-content-sm-around" id="conteudoNavbarSuportado">


            </div>
            <div class="dropdown">
                <a class="btn btn-light dropdown-toggle" href="" role="button" id="dropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   style="color: #333333; ">
                    <img src="~/img/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg"
                         width="65">
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="@Url.Action( "Perfil", "TelaPrincipal")">Perfil</a>
                    <a class="dropdown-item text-danger" href="#">Sair</a>
                </div>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

MaisAprendizado/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="login/site.css">

    <title>Login</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background:#FFFFFF;">
            <a class="navbar-brand" href="#"><img src="img/logo2.png" width="247"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                    aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse justify-content-end" id="conteudoNavbarSuportado">
                <a class="nav-item nav-link" href="#" style="color: #333333;"> <img src="img/25694.svg" width="50"></a>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

MaisAprendizado/Views/Shared/_LayoutPerfil.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="~/css/perfil.css">

    <title>Meu Perfil</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background:#FFFFFF;">
            <a class="navbar-brand" href="#"><img src="~/img/logo2.png" width="247"></a>


            <div class="collapse navbar-collapse justify-content-sm-around" id="conteudoNavbarSuportado">


            </div>
            <div class="dropdown">
                <a class="btn btn-light dropdown-toggle" href="@Url.Action( "Perfil", "TelaPrincipal")" role="button" id="dropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   style="color: #333333; ">
                    <img src="~/img/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg"
                         width="65">
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Perfil</a>
                    <a class="dropdown-item text-danger" href="#">Sair</a>
                </div>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

MaisAprendizado/Views/Shared/_LayoutTelaPrincipal.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="fontawesome/css/all.css">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="~/css/telaPrincipal.css">

    <title>Página Principal</title>
    <link rel="icon" type="" href="img/favicon.png">
</head>

<body>

    <header>
        <!-- Inicio Cabeçalho -->
        <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background:#FFFFFF;">
            <a class="navbar-brand" href="#"><img src="~/img/logo2.png" width="247"></a>


            <div class="collapse navbar-collapse justify-content-sm-around" id="conteudoNavbarSuportado">


            </div>
            <div class="dropdown">
                <a class="btn btn-light dropdown-toggle"  role="button" id="dropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   style="color: #333333; ">
                    <img src="~/img/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg"
                         width="65">
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="@Url.Action( "Perfil", "TelaPrincipal")">Perfil</a>
                    <a class="dropdown-item text-danger" href="#">Sair</a>
                </div>
            </div>
        </nav>




    </header> <!-- Fim Cabeçalho -->

    @RenderBody()


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>