MaisAprendizado/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MaisAprendizado.Models
{
    public class Professor : Pessoa
    {
        public Pessoa Pessoa { get; set; }//is a
        
        [Display(Name = "Crédito")]
        [DataType(DataType.Currency)]
        public decimal Credito { get; set;}
    }
}

MaisAprendizado/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MaisAprendizado.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Seletor()
        {
            return View();
        }
        public IActionResult Aluno()
        {
            return View();
        }
        public IActionResult Professor()
        {
            return View();
        }
    }

}

MaisAprendizado/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaisAprendizado.Data;
using MaisAprendizado.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MaisAprendizado.Controllers
{
    public class ProfessorController : Controller
    {
        // GET: ProfessorController
        public ActionResult Professor(Pessoa pessoa)
        {
            return View(pessoa);
        }

        // GET: ProfessorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProfessorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProfessorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection pessoa)
        {
            int PessoaId = -1;
            string nome = pessoa["nome"];   //<input name = "nome"
            string email = pessoa["email"]; //<input emal = "email"
            string senha = pessoa["senha"]; //<input senha = "senha"
            string dataNascimento = pessoa["datanascimento"];
            string telefone = pessoa["telefone"];
            var dataNasc = DateTime.Parse(dataNascimento);

            var novaPessoa = new Pessoa();
            novaPessoa.Nome =  pessoa["nome"];
            novaPessoa.Email =  pessoa["email"];
            novaPessoa.Senha =  pessoa["senha"];
            novaPessoa.DataNascimento = pessoa["datanascimento"];
            novaPessoa.Telefone =  pessoa["telefone"];

            var professor = new Professor();
            professor.Nome = pessoa["nome"];
            professor.Email = pessoa["email"];
            professor.Senha = pessoa["senha"];
            professor.DataNascimento = pessoa["datanascimento"];
            professor.Telefone = pessoa["telefone"];
            try
            {
                using (var data = new PessoaData())
                 novaPessoa.PessoaId = data.Create(novaPessoa);
                using (var professordata = new ProfessorData())
                    professordata.Create(professor, novaPessoa);
                ViewBag.Message = "Sucesso Cadastro";
                return View();



            }
            catch
            {
                ViewBag.Message = "Erro Cadastro";
                return View();
            }
        }

        // GET: ProfessorController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProfessorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfessorController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProfessorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MaisAprendizado/Views/Professor/Create.cshtml
@model Pessoa

@{
    Layout = "_LayoutCadastroAlunoProfessor";
}


@if (ViewBag.Message == "Erro Cadastro")
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="text-danger">NÃO FOI POSSÍVEL EFETUAR O CADASTRO!</h4>
                    <p>
                        Tente novamente...
                    </p>
                </div>
                <div class="modal-footer">
                    <button onclick="" type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}



<div class="container espacoDiv">
  

    <div class="container-formulario">
        @if (ViewBag.Message == "Sucesso Cadastro")
        {
            <div class="modal-body">
                <h4 class="text-success d-flex justify-content-center">Cadastro efetuado com sucesso!</h4>
            </div>

        }
        @if (ViewBag.Message == "Erro Cadastro")
        {
            
                        <div class="modal-body">
                            <h4 class="text-danger">NÃO FOI POSSÍVEL EFETUAR O CADASTRO!</h4>
                          
                        </div>
                       
        }
        
    </div>

</div>

MaisAprendizado/Views/Professor/Professor.cshtml
@model Pessoa

@{
    Layout = "_LayoutCadastroAlunoProfessor";
}

@if (ViewBag.Message == "Erro Cadastro")
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="text-danger">NÃO FOI POSSÍVEL EFETUAR O CADASTRO!</h4>
                    <p>
                        Tente novamente...
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

@if (ViewBag.Message == "Sucesso Cadastro")
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="text-success">Cadastro efetuado com sucesso!</h4>
                    <p>
                        Tente novamente...
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="container espacoDiv">

    <div class="container-formulario">
        <form asp-controller="Professor" asp-action="Create" method="post">
            <h4 class="text-primary">CRIE SUA CONTA</h4>
            <h6>Preencha o cadastro</h6>
            <hr>
            <div class="form-group">
                <label for="nomeCompleto">Nome Completo</label>
                <input type="text" class="form-control" id="nomeCompleto" asp-for="Nome"
                       placeholder="Digite seu nome" required>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Endereço de email</label>
                <input type="email" class="form-control" asp-for="Email" id="exampleInputEmail1" aria-describedby="emailHelp"
                       placeholder="Seu email" required="true">
            </div>
            <div class="form-row">
                <div class="col">
                    <label for="exampleInputPassword1">Senha</label>
                    <input type="password" asp-for="Senha" class="form-control" id="exampleInputPassword1" placeholder="Senha">

                </div>
                <div class="col">
                    <label for="dataNascimento">Data de Nascimento</label>
                    <input type="date" asp-for="DataNascimento" class="form-control" id="dataNascimento" placeholder="12/08/1999">

                </div>
                <div class="col">
                    <label for="telefone">Telefone</label>
                    <input type="tel" asp-for="Telefone" class="form-control" id="telefone" placeholder="(XX) 00000-0000">

                </div>
            </div>
            <div class="botaoGrupo">
                <div class="">
                    <a asp-controller="Cadastro" asp-action="Seletor">
                        <button type="button" class="btn btn-danger">
                            VOLTAR
                        </button>
                    </a>
                    <button type="submit" class="btn btn-success">

                        SALVAR
                    </button>
                </div>
            </div>
        </form>
    </div>

</div>